FROM alpine:3.1

ADD hello /opt/hello
ADD requirements.txt /opt/hello/requirements.txt

RUN apk add --update python py-pip && \
rm -rf /var/cache/apk/* && \
pip install -r /opt/hello/requirements.txt


CMD python /opt/hello/hello.py
